Documentation:
 Enabled: false
LineLength:
 Max: 99
Style/FrozenStringLiteralComment:
 Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
   - 'spec/**/*.rb'
AllCops:
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
