# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 644fdcc50a39fd9768bb113f3bf49256e80710cf7115e8b1cce5628af2d45885dc63ad761aa7da5f97108c5ea9514ef33205008e0df1371abd259a54c3b544d6
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_username: <%= ENV['MAILER_USERNAME'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  mailer_authentication: <%= ENV['MAILER_AUTHENTICATION'] %>

test:
  secret_key_base: 4651aca9c1ae7e8a469a13708a7ec0f341c2421d2e904a1f326f5b8fdceb0ed87136d1577eca41306b9d145e480a3b9f07877a5b3a1be32c471cf9ef4443c0f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
